---
# Site settings
title: ironswim.pl
tagline: Łukasz Kaczmarski
email: kaczmarskiplywanie@gmail.com
description: "Szkoła pływania"
baseurl: "/ironswim"  # the subpath of your site, e.g. /blog/
url: "https://rzegocki.pl"  # the base hostname & protocol for your site

assets:
    sources:
        - _assets/css
        - _assets/css/_sass
        - _assets/images
        - _assets/js
mainnav:
    - {title: 'Start', url: '/', name: 'index.html'}
    - {title: 'O mnie', url: '/o-mnie', name: 'o-mnie.html'}
    - {title: 'Dla kogo?', url: '/dla-kogo', name: 'dla-kogo.html'}
    - {title: 'Cennik', url: '/cennik', name: 'cennik.html'}
    - {title: 'Lokalizacja', url: '/lokalizacja', name: 'lokalizacja.html'}
    - {title: 'Kontakt', url: '/kontakt', name: 'kontakt.html'}

# Build settings
markdown: kramdown

gems:
  - jekyll-autoprefixer
